#page title
page_title                                : Subway Surfers Mod APK (Latest Version)                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 512939461                               # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://modmenuz.com/mod-apk/subway-surfers/                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                          # Enter Google Play Store URL.
presskit_download_link                    : https://play.google.com/store/apps/details?id=com.kiloo.subwaysurf&gl=us                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Subway Surfers Mod APK                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : FREE DOWNLOAD                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Download Subway Surfers mod apk with everything unblocked.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Sybo Games                    
your_link                                 : https://play.google.com/store/apps/dev?id=7363891306616760846&gl=us                     
your_city                                 : Copenhagen                                
email_address                             : subwaysurfersmodapk@gmail.com
facebook_username                         :                                           
instagram_username                        : subwaysurfers
twitter_username                          : subwaysurfers
github_username                           : subwaysurfers-mod-apk
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Subway Surfers Mod APK
    description                           : Do you love playing Subway Surfers? If yes, then you would be glad to know that there is a Subway Surfers mod apk available that will make your game play even more exciting. With the mod apk, you will get unlimited coins and keys so that you can keep on playing the game without any interruptions. The mod apk is also updated regularly so that you can continue to enjoy all the new features and updates in the game.
    fontawesome_icon_name                 : magic
    
  - title                                 : Everything Unlocked & Unlocked
    description                           : Are you looking for a way to unblock Subway Surfers? If so, you’re in luck! There are several methods you can use, depending on your location. If you’re in the United States, you can use a VPN to unblock the game. A VPN will encrypt your traffic and route it through a server in a location of your choice. This will allow you to access content that is blocked in your location. If you’re not in the United States, you can use a proxy server to unblock Subway Surfers. A proxy server will redirect your traffic through its own servers, allowing you to access content that is blocked in your location.
    fontawesome_icon_name                 : mobile

  - title                                 : Subway Surfers Mod Menu
    description                           : Subway Surfers is a popular endless runner game for Android and iOS devices. The premise of the game is to help Jake, Tricky and Fresh escape from the grumpy Inspector and his dog. Players run along a subway track, dodging oncoming obstacles. The game has been downloaded over 1 billion times and is one of the most popular mobile games available. One of the reasons for Subway Surfers' popularity is the ability to mod the game. A mod menu allows players to change various aspects of the game, such as their character's appearance, how many coins they start with, and more. There are also mods that allow players to play as different characters or modify the track layout. While some mods can be found on unofficial websites, there are also several official mod menus available.
    fontawesome_icon_name                 : play-circle


# Theme Settings
topbar_color                              : "#0080b4"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#02649c"
cover_overlay_transparency                : 0.75

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
